### Create message
POST http://localhost:3000/messages 
Content-Type: application/json

{
    "content": "false"
}


### Get a particular message
GET http://localhost:3000/messages/20  

### Get all
GET http://localhost:3000/messages